def init(app_name: str) -> bool: ...


class Notification:
    @classmethod
    def new(cls, title: str, message: str, icon: str) -> Notification: ...
    def set_timeout(self, timeout: int) -> None: ...
    def show(self) -> bool: ...
